---
# tasks file for ./roles/Layer2_Interface_config
- name: Enable Interfaces
  tags: [L2]
  loop: "{{ l3_fabric.interfaces }}"
  ios_interfaces:
   config:
    - name: "{{ item.name }}"
      description: "{{ item.desc }}"
      enabled: true
#      speed: 100
 #     duplex: half
#- name: Enable Loopback Interface description
#  tags: [L2]
#  loop: "{{ local_loopbacks }}"
#  ios_interfaces:
#   config:
#    - name: "{{ item.name }}"
#      description: "{{ item.desc }}"
#      enabled: true
- name: Configure L2-vlan on Switch
  tags: [L2]
  when: inventory_hostname=='Core-SW01' or inventory_hostname=='Core-SW02' 
  loop: "{{ L2_vlan }}"
  cisco.ios.ios_vlans:
    config:
    - name: "{{ item.name }}"
      vlan_id: "{{ item.vlan_id }}"
      state: active
      shutdown: disabled
    state: merged

- name: Configure vlan to Switchport interfaces on Core SW 01
  tags: [L2]
  when: inventory_hostname=='Core-SW01'
  cisco.ios.ios_l2_interfaces:
    config:
    - name: e1/1
      mode: access
      access:
        vlan: 32
    state: merged
- name: Configure vlan to Switchport interfaces on Core SW 02
  tags: [L2]
  when: inventory_hostname=='Core-SW02'
  cisco.ios.ios_l2_interfaces:
    config:
    - name: e1/1
      mode: access
      access:
        vlan: 12
    state: merged
- name: Configure port-channel on core switches
  tags: [L2]
  when: inventory_hostname=='Core-SW01' or inventory_hostname=='Core-SW02'
  cisco.ios.ios_config:
    lines:
    - interface range eth0/3, eth1/3
    - desc port-channel to core switch
    - channel-group 10 mode active
#    parents: interface Ethernet0/3
- name: Configure Trunk on all port-channel 
  tags: [L2]
  when: inventory_hostname=='Core-SW01' or inventory_hostname=='Core-SW02'
  loop: "{{ l2_fabric.interface }}"
  cisco.ios.ios_l2_interfaces:
    config:
    - name: "{{ item.name }}"
      mode: trunk
      trunk:
        allowed_vlans: 10-100
        encapsulation: dot1q
    state: merged