---
# tasks file for ./roles/Layer2_Interface_config
- name: Configure L2-vlan on Switch
  tags: [L2]
  when: inventory_hostname=='Core-SW01' or inventory_hostname=='Core-SW02' or inventory_hostname=='Access-SW03'
  loop: "{{ L2_vlan }}"
  cisco.ios.ios_vlans:
    config:
    - name: "{{ item.name }}"
      vlan_id: "{{ item.vlan_id }}"
      state: active
      shutdown: disabled
    state: merged

#- name: Asssign vlan to interfaces on Switches
#  tags: [L2]
#  when: inventory_hostname=='Core-SW01'
#  cisco.ios.ios_l2_interfaces:
#    config:
#    - name: e1/1
#      mode: access
#      access:
#        vlan: 32
#    state: merged
- name: Asssign vlan to interfaces on Switches
  tags: [L2]
  when: inventory_hostname=='Core-SW02' or inventory_hostname=='Core-SW01' or inventory_hostname=='Access-SW03'
  loop: "{{ access_ports }}"
  cisco.ios.ios_l2_interfaces:
    config:
    - name: "{{ item.name }}"
      mode: "{{ item.mode }}"
      access:
        vlan: "{{ item.vlan }}"
    state: merged
- name: Configure port-channel on core switches
  tags: [PO, L2]
  when: inventory_hostname=='Core-SW01' or inventory_hostname=='Core-SW02'
  cisco.ios.ios_config:
    lines:
    - interface range eth0/3, eth1/3
    - desc port-channel to core switch
    - channel-group 10 mode active
    - interface range eth1/0, eth1/2
    - desc port-channel to access switch
    - channel-group 20 mode active

- name: Configure port-channel on Access-Switch
  tags: [PO, L2]
  when: inventory_hostname=='Access-SW03'
  cisco.ios.ios_config:
    lines:
    - interface range eth1/0, eth1/2
    - desc port-channel to core switch 01
    - channel-group 10 mode active
    - interface range eth0/0, eth0/2
    - desc port-channel to core switch 02
    - channel-group 20 mode active
#    parents: interface Ethernet0/3

- name: Enable trunk on port-channels
  tags: [trunk, L2, PO]
  when: inventory_hostname=='Core-SW01' or inventory_hostname=='Core-SW02' or inventory_hostname=='Access-SW03'
  loop: "{{ l2_fabric.interface }}"
  cisco.ios.ios_l2_interfaces:
    config:
    - name: "{{ item.name }}"
      mode: trunk
      trunk:
        allowed_vlans: 10-100
        encapsulation: dot1q
    state: merged