---
- name: Deploying FHRP
  connection: network_cli
  gather_facts: False
  hosts: all
  tasks:
    - name: Save generated configuration
      template:
        src: "templates/fhrp.j2"
        dest: "templates/{{ inventory_hostname}}.conf"

    - name: Configure HSRP/VRRP
      ios_config:
        src: "templates/fhrp.j2"
    - name: save running to startup when modified
      cisco.ios.ios_config:
        save_when: modified