---
# tasks file for ./roles/Layer3_Interface_config
- name: Configure Layer 3 Interfaces
  tags: [L3]
  when: inventory_hostname!= 'Access-SW03'
  loop: "{{ l3_fabric.interfaces }}"
  ios_l3_interface:
   name: "{{ item.name }}"
   ipv4: "{{ item.ip_address }}"
   
- name: Enable Interfaces
  tags: [L3]
  when: inventory_hostname!= 'Access-SW03'
  loop: "{{ l3_fabric.interfaces }}"
  ios_interfaces:
   config:
    - name: "{{ item.name }}"
      description: "{{ item.desc }}"
      enabled: true