---
local_loopbacks:
    - name: Loopback11
      desc: Sample Network Route Injection
      ip_address: 172.21.0.1/24
#      prefix: 24
    - name: Loopback12
      desc: Sample Network Route Injection
      ip_address: 172.21.1.1/24
#      prefix: 24
    - name: Loopback10
      desc: Sample Network Route Injection
      ip_address: 10.10.10.10/32

l3_fabric:
    interfaces:
        - name: e0/2
          desc: L3 Link to RTR02
          ip_address: 172.16.0.1/30
         # prefix: 30
        - name: e1/0
          desc: L3 Link to RTR03
          ip_address: 172.16.0.9/30
         # prefix: 30
        - name: e0/1
          desc: L3 Link to RTR04
          ip_address: 172.16.0.17/30

as_number: 65000
log_neighbor_changes: true
router_id: 192.168.1.1
         
neighbor:
-   address: 172.16.0.2
    remote_as: 65000
-   address: 172.16.0.10
    remote_as: 65001
-   address: 172.16.0.18
    remote_as: 65001

networks:
- prefix: 172.21.0.1
  masklen: 24
- prefix: 172.21.1.1
  masklen: 24
- prefix: 10.10.10.10
  masklen: 32

