---
local_loopbacks:
    - name: Loopback11
      desc: Sample Network Route Injection
      ip_address: 172.24.0.1/24
#      prefix: 24
    - name: Loopback12
      desc: Sample Network Route Injection
      ip_address: 172.24.1.1/24
#      prefix: 24

l3_fabric:
    interfaces:
        - name: e0/1
          desc: L3 Link to RTR01
          ip_address: 172.16.0.18/30
         # prefix: 30
        - name: e1/0
          desc: L3 Link to RTR02
          ip_address: 172.16.0.6/30
         # prefix: 30
        - name: e0/2
          desc: L3 Link to Core-SW1
          ip_address: 172.16.0.25/30
        - name: e0/3
          desc: L3 Link to RTR03
          ip_address: 172.16.0.22/30
ospf_router_id: 4.4.4.4
ospf_networks:
    - network: 172.16.0.20
      mask: 0.0.0.3
      area: 0
    - network: 172.16.0.16
      mask: 0.0.0.3
      area: 0
    - network: 172.16.0.4
      mask: 0.0.0.3
      area: 0
    - network: 172.16.0.24
      mask: 0.0.0.3
      area: 0
    - network: 172.24.0.0
      mask: 0.0.1.255
      area: 0
    - network: 4.4.4.4
      mask: 0.0.0.0
      area: 0
router_id: 192.168.4.4
neighbor:
-   address: 172.16.0.5
    remote_as: 65000
-   address: 172.16.0.17
    remote_as: 65000
-   address: 172.16.0.21
    remote_as: 65001
as_number: 65001
