---
local_loopbacks:
    - name: Loopback11
      desc: Sample Network Route Injection
      ip_address: 172.22.0.1/24
#      prefix: 24
    - name: Loopback12
      desc: Sample Network Route Injection
      ip_address: 172.22.1.1/24
#      prefix: 24
    - name: Loopback10
      desc: Sample Network Route Injection
      ip_address: 10.10.20.20/32

l3_fabric:
    interfaces:
        - name: Gi0/0
          desc: L3 Link to RTR01
          ip_address: 172.16.0.2/30
         # prefix: 30
        - name: Gi0/1
          desc: L3 Link to RTR04
          ip_address: 172.16.0.5/30
         # prefix: 30
        - name: Gi0/2
          desc: L3 Link to RTR03
          ip_address: 172.16.0.13/30

as_number: 65000
router_id: 192.168.2.2
neighbor:
-   address: 172.16.0.1
    remote_as: 65000
-   address: 172.16.0.6
    remote_as: 65001
-   address: 172.16.0.14
    remote_as: 65001    
networks:
- prefix: 172.22.0.1
  masklen: 24
- prefix: 172.22.1.1
  masklen: 24
- prefix: 10.10.20.20
  masklen: 32
  